import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ko' | 'ar';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Footer translations
    'footer.aboutUs': 'About Us',
    'footer.contactUs': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.disclaimer': 'Disclaimer',
    'footer.didYouKnow': 'Did You Know',
    'footer.learnMore': 'Learn More',
    'footer.newFeature': 'New Feature',
    'footer.trending': 'Trending',
    'footer.events': 'Events',
    'footer.joinCommunity': 'Join Our Community',
    'footer.subscribe': 'Subscribe',
    'footer.enterEmail': 'Enter your email',
    'footer.subscribing': 'Subscribing...',
    'footer.subscriptionText': 'Get the latest crypto news and market updates delivered to your inbox',
    'footer.copyright': '© Copyright 2025',
    'footer.companyDescription': 'CoinClarity is a versatile platform that shares the best, real-time, highest quality cryptocurrency market data. With an easy-to-use API, charts, and cryptocurrency glossary.',
    
    // Common translations
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.readMore': 'Read More',
    'common.readLess': 'Read Less',
    
    // News related translations
    'news.latest': 'Latest News',
    'news.trending': 'Trending News',
    'news.exclusive': 'Exclusive News',
    'news.press': 'Press News',
    'news.market': 'Market News',
    'news.crypto': 'Cryptocurrency',
    'news.blockchain': 'Blockchain',
    'news.defi': 'DeFi',
    'news.nft': 'NFT',
    'news.marketCap': 'Market Cap',
    'news.price': 'Price',
    'news.change': 'Change',
    'news.volume': 'Volume',
    'news.supply': 'Supply',
    'news.trendingTitle': 'Trending News',
    'news.readMore': 'Read More',
    'news.readFullArticle': 'Read Full Article',
    'news.latestPressNews': 'Latest Press & News',
    'news.stayUpdated': 'Stay updated with the latest developments and announcements',
    
    // Explore section
    'explore.didYouKnow': 'Did You Know?',
    'explore.learnALittle': 'Learn a Little',
    'explore.testKnowledge': 'Test Knowledge',
    
    // Navigation translations
    'nav.home': 'Home',
    'nav.news': 'News',
    'nav.blog': 'Blog',
    'nav.market': 'Market',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.dashboard': 'Dashboard',
    
    // Form translations
    'form.email': 'Email',
    'form.password': 'Password',
    'form.name': 'Name',
    'form.message': 'Message',
    'form.required': 'This field is required',
    'form.invalidEmail': 'Please enter a valid email address',
    'form.passwordLength': 'Password must be at least 6 characters',
    'form.confirmPassword': 'Confirm Password',
    'form.passwordsNotMatch': 'Passwords do not match',
    
    // Error messages
    'error.network': 'Network error. Please check your connection and try again.',
    'error.general': 'Something went wrong. Please try again.',
    'error.notFound': 'Page not found.',
    'error.unauthorized': 'You are not authorized to access this page.',
    'error.server': 'Server error. Please try again later.',
    
    // Success messages
    'success.subscription': 'Successfully subscribed to newsletter!',
    'success.login': 'Successfully logged in!',
    'success.logout': 'Successfully logged out!',
    'success.save': 'Successfully saved!',
    'success.delete': 'Successfully deleted!',
  },
  hi: {
    // Footer translations in Hindi
    'footer.aboutUs': 'हमारे बारे में',
    'footer.contactUs': 'संपर्क करें',
    'footer.faq': 'सामान्य प्रश्न',
    'footer.privacyPolicy': 'गोपनीयता नीति',
    'footer.disclaimer': 'अस्वीकरण',
    'footer.didYouKnow': 'क्या आप जानते हैं',
    'footer.learnMore': 'और जानें',
    'footer.newFeature': 'नई सुविधा',
    'footer.trending': 'ट्रेंडिंग',
    'footer.events': 'घटनाएं',
    'footer.joinCommunity': 'हमारे समुदाय में शामिल हों',
    'footer.subscribe': 'सदस्यता लें',
    'footer.enterEmail': 'अपना ईमेल दर्ज करें',
    'footer.subscribing': 'सदस्यता ले रहे हैं...',
    'footer.subscriptionText': 'अपने इनबॉक्स में नवीनतम क्रिप्टो समाचार और बाजार अपडेट प्राप्त करें',
    'footer.copyright': '© कॉपीराइट 2025',
    'footer.companyDescription': 'कॉइनक्लैरिटी एक बहुमुखी प्लेटफॉर्म है जो सर्वोत्तम, रीयल-टाइम, उच्चतम गुणवत्ता वाले क्रिप्टोकरेंसी बाजार डेटा साझा करता है। आसान-से-उपयोग API, चार्ट और क्रिप्टोकरेंसी शब्दकोश के साथ।',
    
    // Common translations in Hindi
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.submit': 'जमा करें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.readMore': 'और पढ़ें',
    'common.readLess': 'कम पढ़ें',
    
    // News related translations in Hindi
    'news.latest': 'नवीनतम समाचार',
    'news.trending': 'ट्रेंडिंग समाचार',
    'news.exclusive': 'विशेष समाचार',
    'news.press': 'प्रेस समाचार',
    'news.market': 'बाजार समाचार',
    'news.crypto': 'क्रिप्टोकरेंसी',
    'news.blockchain': 'ब्लॉकचेन',
    'news.defi': 'डीफाई',
    'news.nft': 'एनएफटी',
    
    // Navigation translations in Hindi
    'nav.home': 'होम',
    'nav.news': 'समाचार',
    'nav.blog': 'ब्लॉग',
    'nav.market': 'बाजार',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    'nav.admin': 'एडमिन',
    'nav.dashboard': 'डैशबोर्ड',
    
    // Form translations in Hindi
    'form.email': 'ईमेल',
    'form.password': 'पासवर्ड',
    'form.name': 'नाम',
    'form.message': 'संदेश',
    'form.required': 'यह फ़ील्ड आवश्यक है',
    'form.invalidEmail': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'form.passwordLength': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'form.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'form.passwordsNotMatch': 'पासवर्ड मेल नहीं खाते',
    
    // Error messages in Hindi
    'error.network': 'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    'error.general': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
    'error.notFound': 'पृष्ठ नहीं मिला।',
    'error.server': 'सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।',
    
    // Success messages in Hindi
    'success.subscription': 'न्यूजलेटर की सदस्यता सफलतापूर्वक ली गई!',
    'success.login': 'सफलतापूर्वक लॉगिन हो गया!',
    'success.logout': 'सफलतापूर्वक लॉगआउट हो गया!',
    'success.save': 'सफलतापूर्वक सहेजा गया!',
    'success.delete': 'सफलतापूर्वक हटा दिया गया!',
    
    // News content translations in Hindi
    'news.exclusiveTitle': 'विशेष समाचार',
    'news.viewAll': 'सभी देखें',
    'news.noNewsAvailable': 'कोई समाचार उपलब्ध नहीं है।',
    'news.by': 'द्वारा',
    'news.unknownAuthor': 'अज्ञात लेखक',
    'news.unknownDate': 'अज्ञात तिथि',
    'news.marketData': 'बाजार डेटा',
    'news.cryptocurrency': 'क्रिप्टोकरेंसी',
    'news.nftMarket': 'एनएफटी बाजार',
    'news.viewChart': 'चार्ट देखें',
    'news.close': 'बंद करें',
    'news.timeRange': 'समय सीमा',
    'news.rank': 'रैंक',
    'news.symbol': 'प्रतीक',
    'news.name': 'नाम',
    'news.supply': 'आपूर्ति',
    'news.maxSupply': 'अधिकतम आपूर्ति',
    'news.marketCap': 'बाजार पूंजी',
    'news.volume24h': '24 घंटे का वॉल्यूम',
    'news.price': 'मूल्य',
    'news.change24h': '24 घंटे में परिवर्तन',
    'news.floorPrice': 'फ्लोर मूल्य',
    'news.floorPriceChange': 'फ्लोर मूल्य परिवर्तन',
    'news.showAll': 'सभी दिखाएं',
    'news.showLess': 'कम दिखाएं',
    'news.loading': 'लोड हो रहा है...',
    'news.error': 'त्रुटि',
    'news.retry': 'पुनः प्रयास करें',
    'news.trendingTitle': 'ट्रेंडिंग न्यूज़',
    'news.readMore': 'और पढ़ें',
    'news.readFullArticle': 'पूरा लेख पढ़ें',
    'news.latestPressNews': 'नवीनतम प्रेस और न्यूज़',
    'news.stayUpdated': 'नवीनतम घटनाक्रम और घोषणाओं के साथ अपडेट रहें',
    
    // Explore section in Hindi
    'explore.didYouKnow': 'क्या आप जानते हैं?',
    'explore.learnALittle': 'थोड़ा सीखें',
    'explore.testKnowledge': 'ज्ञान का परीक्षण करें',
  },
  es: {
    // Spanish translations
    'footer.aboutUs': 'Acerca de nosotros',
    'footer.contactUs': 'Contáctanos',
    'footer.faq': 'Preguntas frecuentes',
    'footer.privacyPolicy': 'Política de privacidad',
    'footer.disclaimer': 'Descargo de responsabilidad',
    'footer.didYouKnow': '¿Sabías que?',
    'footer.learnMore': 'Aprende más',
    'footer.newFeature': 'Nueva función',
    'footer.trending': 'Tendencias',
    'footer.events': 'Eventos',
    'footer.joinCommunity': 'Únete a nuestra comunidad',
    'footer.subscribe': 'Suscribirse',
    'footer.enterEmail': 'Ingresa tu email',
    'footer.subscribing': 'Suscribiendo...',
    'footer.subscriptionText': 'Recibe las últimas noticias de cripto y actualizaciones del mercado en tu bandeja de entrada',
    'footer.copyright': '© Copyright 2025',
    'footer.companyDescription': 'CoinClarity es una plataforma versátil que comparte los mejores datos del mercado de criptomonedas en tiempo real y de la más alta calidad. Con una API fácil de usar, gráficos y glosario de criptomonedas.',
    
    'news.exclusiveTitle': 'Noticias Exclusivas',
    'news.viewAll': 'Ver Todo',
    'news.noNewsAvailable': 'No hay noticias disponibles.',
    'news.by': 'Por',
    'news.unknownAuthor': 'Autor desconocido',
    'news.unknownDate': 'Fecha desconocida',
    'news.marketData': 'Datos del Mercado',
    'news.cryptocurrency': 'Criptomonedas',
    'news.nftMarket': 'Mercado NFT',
    'news.viewChart': 'Ver Gráfico',
    'news.close': 'Cerrar',
    'news.timeRange': 'Rango de Tiempo',
    'news.rank': 'Rango',
    'news.symbol': 'Símbolo',
    'news.name': 'Nombre',
    'news.supply': 'Suministro',
    'news.maxSupply': 'Suministro Máximo',
    'news.marketCap': 'Capitalización de Mercado',
    'news.volume24h': 'Volumen 24h',
    'news.price': 'Precio',
    'news.change24h': 'Cambio 24h',
    'news.floorPrice': 'Precio Mínimo',
    'news.floorPriceChange': 'Cambio Precio Mínimo',
    'news.showAll': 'Mostrar Todo',
    'news.showLess': 'Mostrar Menos',
    'news.loading': 'Cargando...',
    'news.error': 'Error',
    'news.retry': 'Reintentar',
    'news.trendingTitle': 'Noticias de Tendencia',
    'news.readMore': 'Leer Más',
    'news.readFullArticle': 'Leer Artículo Completo',
    'news.latestPressNews': 'Últimas Noticias de Prensa',
    'news.stayUpdated': 'Mantente actualizado con los últimos desarrollos y anuncios',
    
    // Explore section in Spanish
    'explore.didYouKnow': '¿Sabías que?',
    'explore.learnALittle': 'Aprende un Poco',
    'explore.testKnowledge': 'Prueba tu Conocimiento',
  },
  fr: {
    // French translations
    'footer.aboutUs': 'À propos de nous',
    'footer.contactUs': 'Contactez-nous',
    'footer.faq': 'FAQ',
    'footer.privacyPolicy': 'Politique de confidentialité',
    'footer.disclaimer': 'Avertissement',
    'footer.didYouKnow': 'Le saviez-vous ?',
    'footer.learnMore': 'En savoir plus',
    'footer.newFeature': 'Nouvelle fonctionnalité',
    'footer.trending': 'Tendances',
    'footer.events': 'Événements',
    'footer.joinCommunity': 'Rejoignez notre communauté',
    'footer.subscribe': 'S\'abonner',
    'footer.enterEmail': 'Entrez votre email',
    'footer.subscribing': 'Abonnement...',
    'footer.subscriptionText': 'Recevez les dernières nouvelles crypto et mises à jour du marché dans votre boîte de réception',
    'footer.copyright': '© Copyright 2025',
    'footer.companyDescription': 'CoinClarity est une plateforme polyvalente qui partage les meilleures données de marché de cryptomonnaies en temps réel et de la plus haute qualité. Avec une API facile à utiliser, des graphiques et un glossaire de cryptomonnaies.',
    
    'news.exclusiveTitle': 'Actualités Exclusives',
    'news.viewAll': 'Voir Tout',
    'news.noNewsAvailable': 'Aucune actualité disponible.',
    'news.by': 'Par',
    'news.unknownAuthor': 'Auteur inconnu',
    'news.unknownDate': 'Date inconnue',
    'news.marketData': 'Données du Marché',
    'news.cryptocurrency': 'Cryptomonnaies',
    'news.nftMarket': 'Marché NFT',
    'news.viewChart': 'Voir le Graphique',
    'news.close': 'Fermer',
    'news.timeRange': 'Plage de Temps',
    'news.rank': 'Rang',
    'news.symbol': 'Symbole',
    'news.name': 'Nom',
    'news.supply': 'Offre',
    'news.maxSupply': 'Offre Maximale',
    'news.marketCap': 'Capitalisation Boursière',
    'news.volume24h': 'Volume 24h',
    'news.price': 'Prix',
    'news.change24h': 'Changement 24h',
    'news.floorPrice': 'Prix Plancher',
    'news.floorPriceChange': 'Changement Prix Plancher',
    'news.showAll': 'Afficher Tout',
    'news.showLess': 'Afficher Moins',
    'news.loading': 'Chargement...',
    'news.error': 'Erreur',
    'news.retry': 'Réessayer',
    'news.trendingTitle': 'Actualités Tendances',
    'news.readMore': 'Lire Plus',
    'news.readFullArticle': 'Lire l\'Article Complet',
    'news.latestPressNews': 'Dernières Actualités de Presse',
    'news.stayUpdated': 'Restez informé des derniers développements et annonces',
    
    // Explore section in French
    'explore.didYouKnow': 'Le Saviez-Vous ?',
    'explore.learnALittle': 'Apprenez un Peu',
    'explore.testKnowledge': 'Testez vos Connaissances',
  },
  de: {
    // German translations
    'footer.aboutUs': 'Über uns',
    'footer.contactUs': 'Kontakt',
    'footer.faq': 'FAQ',
    'footer.privacyPolicy': 'Datenschutzrichtlinie',
    'footer.disclaimer': 'Haftungsausschluss',
    'footer.didYouKnow': 'Wussten Sie schon?',
    'footer.learnMore': 'Mehr erfahren',
    'footer.newFeature': 'Neue Funktion',
    'footer.trending': 'Trends',
    'footer.events': 'Veranstaltungen',
    'footer.joinCommunity': 'Treten Sie unserer Community bei',
    'footer.subscribe': 'Abonnieren',
    'footer.enterEmail': 'E-Mail eingeben',
    'footer.subscribing': 'Abonniere...',
    'footer.subscriptionText': 'Erhalten Sie die neuesten Krypto-Nachrichten und Markt-Updates in Ihrem Posteingang',
    'footer.copyright': '© Copyright 2025',
    'footer.companyDescription': 'CoinClarity ist eine vielseitige Plattform, die die besten, Echtzeit-Daten des Kryptowährungsmarktes in höchster Qualität teilt. Mit einer einfach zu bedienenden API, Charts und einem Kryptowährungs-Glossar.',
    
    'news.exclusiveTitle': 'Exklusive Nachrichten',
    'news.viewAll': 'Alle anzeigen',
    'news.noNewsAvailable': 'Keine Nachrichten verfügbar.',
    'news.by': 'Von',
    'news.unknownAuthor': 'Unbekannter Autor',
    'news.unknownDate': 'Unbekanntes Datum',
    'news.marketData': 'Marktdaten',
    'news.cryptocurrency': 'Kryptowährungen',
    'news.nftMarket': 'NFT-Markt',
    'news.viewChart': 'Chart anzeigen',
    'news.close': 'Schließen',
    'news.timeRange': 'Zeitbereich',
    'news.rank': 'Rang',
    'news.symbol': 'Symbol',
    'news.name': 'Name',
    'news.supply': 'Angebot',
    'news.maxSupply': 'Maximales Angebot',
    'news.marketCap': 'Marktkapitalisierung',
    'news.volume24h': '24h Volumen',
    'news.price': 'Preis',
    'news.change24h': '24h Änderung',
    'news.floorPrice': 'Mindestpreis',
    'news.floorPriceChange': 'Mindestpreis-Änderung',
    'news.showAll': 'Alle anzeigen',
    'news.showLess': 'Weniger anzeigen',
    'news.loading': 'Laden...',
    'news.error': 'Fehler',
    'news.retry': 'Wiederholen',
    'news.trendingTitle': 'Trend-Nachrichten',
    'news.readMore': 'Mehr Lesen',
    'news.readFullArticle': 'Vollständigen Artikel Lesen',
    'news.latestPressNews': 'Neueste Presse- und Nachrichten',
    'news.stayUpdated': 'Bleiben Sie über die neuesten Entwicklungen und Ankündigungen informiert',
    
    // Explore section in German
    'explore.didYouKnow': 'Wussten Sie schon?',
    'explore.learnALittle': 'Lernen Sie ein Wenig',
    'explore.testKnowledge': 'Testen Sie Ihr Wissen',
  },
  zh: {
    // Chinese translations
    'footer.aboutUs': '关于我们',
    'footer.contactUs': '联系我们',
    'footer.faq': '常见问题',
    'footer.privacyPolicy': '隐私政策',
    'footer.disclaimer': '免责声明',
    'footer.didYouKnow': '你知道吗？',
    'footer.learnMore': '了解更多',
    'footer.newFeature': '新功能',
    'footer.trending': '趋势',
    'footer.events': '事件',
    'footer.joinCommunity': '加入我们的社区',
    'footer.subscribe': '订阅',
    'footer.enterEmail': '输入您的邮箱',
    'footer.subscribing': '订阅中...',
    'footer.subscriptionText': '在您的收件箱中获取最新的加密货币新闻和市场更新',
    'footer.copyright': '© 版权所有 2025',
    'footer.companyDescription': 'CoinClarity是一个多功能平台，分享最佳、实时、最高质量的加密货币市场数据。具有易于使用的API、图表和加密货币词汇表。',
    
    'news.exclusiveTitle': '独家新闻',
    'news.viewAll': '查看全部',
    'news.noNewsAvailable': '暂无新闻。',
    'news.by': '作者',
    'news.unknownAuthor': '未知作者',
    'news.unknownDate': '未知日期',
    'news.marketData': '市场数据',
    'news.cryptocurrency': '加密货币',
    'news.nftMarket': 'NFT市场',
    'news.viewChart': '查看图表',
    'news.close': '关闭',
    'news.timeRange': '时间范围',
    'news.rank': '排名',
    'news.symbol': '符号',
    'news.name': '名称',
    'news.supply': '供应量',
    'news.maxSupply': '最大供应量',
    'news.marketCap': '市值',
    'news.volume24h': '24小时交易量',
    'news.price': '价格',
    'news.change24h': '24小时变化',
    'news.floorPrice': '底价',
    'news.floorPriceChange': '底价变化',
    'news.showAll': '显示全部',
    'news.showLess': '显示更少',
    'news.loading': '加载中...',
    'news.error': '错误',
    'news.retry': '重试',
    'news.trendingTitle': '热门新闻',
    'news.readMore': '阅读更多',
    'news.readFullArticle': '阅读完整文章',
    'news.latestPressNews': '最新新闻和公告',
    'news.stayUpdated': '及时了解最新发展和公告',
    
    // Explore section in Chinese
    'explore.didYouKnow': '你知道吗？',
    'explore.learnALittle': '学一点',
    'explore.testKnowledge': '测试知识',
  },
  ja: {
    // Japanese translations
    'footer.aboutUs': '私たちについて',
    'footer.contactUs': 'お問い合わせ',
    'footer.faq': 'よくある質問',
    'footer.privacyPolicy': 'プライバシーポリシー',
    'footer.disclaimer': '免責事項',
    'footer.didYouKnow': 'ご存知でしたか？',
    'footer.learnMore': '詳しく見る',
    'footer.newFeature': '新機能',
    'footer.trending': 'トレンド',
    'footer.events': 'イベント',
    'footer.joinCommunity': 'コミュニティに参加',
    'footer.subscribe': '購読',
    'footer.enterEmail': 'メールアドレスを入力',
    'footer.subscribing': '購読中...',
    'footer.subscriptionText': '最新の暗号通貨ニュースと市場の更新情報をメールボックスで受け取る',
    'footer.copyright': '© 著作権 2025',
    'footer.companyDescription': 'CoinClarityは、最高品質のリアルタイム暗号通貨市場データを共有する多機能プラットフォームです。使いやすいAPI、チャート、暗号通貨用語集を備えています。',
    
    'news.exclusiveTitle': '独占ニュース',
    'news.viewAll': 'すべて表示',
    'news.noNewsAvailable': 'ニュースがありません。',
    'news.by': '著者',
    'news.unknownAuthor': '不明な著者',
    'news.unknownDate': '不明な日付',
    'news.marketData': '市場データ',
    'news.cryptocurrency': '暗号通貨',
    'news.nftMarket': 'NFT市場',
    'news.viewChart': 'チャートを表示',
    'news.close': '閉じる',
    'news.timeRange': '時間範囲',
    'news.rank': 'ランク',
    'news.symbol': 'シンボル',
    'news.name': '名前',
    'news.supply': '供給量',
    'news.maxSupply': '最大供給量',
    'news.marketCap': '時価総額',
    'news.volume24h': '24時間取引量',
    'news.price': '価格',
    'news.change24h': '24時間変化',
    'news.floorPrice': '最低価格',
    'news.floorPriceChange': '最低価格変化',
    'news.showAll': 'すべて表示',
    'news.showLess': '少なく表示',
    'news.loading': '読み込み中...',
    'news.error': 'エラー',
    'news.retry': '再試行',
    'news.trendingTitle': 'トレンドニュース',
    'news.readMore': '続きを読む',
    'news.readFullArticle': '記事全文を読む',
    'news.latestPressNews': '最新のプレスリリースとニュース',
    'news.stayUpdated': '最新の開発と発表について最新情報を入手',
    
    // Explore section in Japanese
    'explore.didYouKnow': 'ご存知でしたか？',
    'explore.learnALittle': '少し学ぶ',
    'explore.testKnowledge': '知識をテスト',
  },
  ko: {
    // Korean translations
    'footer.aboutUs': '회사 소개',
    'footer.contactUs': '연락처',
    'footer.faq': '자주 묻는 질문',
    'footer.privacyPolicy': '개인정보 처리방침',
    'footer.disclaimer': '면책 조항',
    'footer.didYouKnow': '알고 계셨나요?',
    'footer.learnMore': '더 알아보기',
    'footer.newFeature': '새로운 기능',
    'footer.trending': '트렌드',
    'footer.events': '이벤트',
    'footer.joinCommunity': '커뮤니티에 참여',
    'footer.subscribe': '구독',
    'footer.enterEmail': '이메일을 입력하세요',
    'footer.subscribing': '구독 중...',
    'footer.subscriptionText': '최신 암호화폐 뉴스와 시장 업데이트를 받은 편지함에서 받으세요',
    'footer.copyright': '© 저작권 2025',
    'footer.companyDescription': 'CoinClarity는 최고 품질의 실시간 암호화폐 시장 데이터를 공유하는 다목적 플랫폼입니다. 사용하기 쉬운 API, 차트, 암호화폐 용어집을 제공합니다.',
    
    'news.exclusiveTitle': '독점 뉴스',
    'news.viewAll': '모두 보기',
    'news.noNewsAvailable': '사용 가능한 뉴스가 없습니다.',
    'news.by': '작성자',
    'news.unknownAuthor': '알 수 없는 작성자',
    'news.unknownDate': '알 수 없는 날짜',
    'news.marketData': '시장 데이터',
    'news.cryptocurrency': '암호화폐',
    'news.nftMarket': 'NFT 시장',
    'news.viewChart': '차트 보기',
    'news.close': '닫기',
    'news.timeRange': '시간 범위',
    'news.rank': '순위',
    'news.symbol': '심볼',
    'news.name': '이름',
    'news.supply': '공급량',
    'news.maxSupply': '최대 공급량',
    'news.marketCap': '시가총액',
    'news.volume24h': '24시간 거래량',
    'news.price': '가격',
    'news.change24h': '24시간 변화',
    'news.floorPrice': '최저가',
    'news.floorPriceChange': '최저가 변화',
    'news.showAll': '모두 표시',
    'news.showLess': '덜 표시',
    'news.loading': '로딩 중...',
    'news.error': '오류',
    'news.retry': '재시도',
    'news.trendingTitle': '트렌딩 뉴스',
    'news.readMore': '더 보기',
    'news.readFullArticle': '전체 기사 읽기',
    'news.latestPressNews': '최신 보도자료 및 뉴스',
    'news.stayUpdated': '최신 개발 및 발표에 대한 최신 정보를 받으세요',
    
    // Explore section in Korean
    'explore.didYouKnow': '알고 계셨나요?',
    'explore.learnALittle': '조금 배우기',
    'explore.testKnowledge': '지식 테스트',
  },
  ar: {
    // Arabic translations
    'footer.aboutUs': 'من نحن',
    'footer.contactUs': 'اتصل بنا',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.disclaimer': 'إخلاء المسؤولية',
    'footer.didYouKnow': 'هل تعلم؟',
    'footer.learnMore': 'اعرف المزيد',
    'footer.newFeature': 'ميزة جديدة',
    'footer.trending': 'رائج',
    'footer.events': 'الأحداث',
    'footer.joinCommunity': 'انضم إلى مجتمعنا',
    'footer.subscribe': 'اشترك',
    'footer.enterEmail': 'أدخل بريدك الإلكتروني',
    'footer.subscribing': 'جاري الاشتراك...',
    'footer.subscriptionText': 'احصل على أحدث أخبار العملات المشفرة وتحديثات السوق في صندوق الوارد الخاص بك',
    'footer.copyright': '© حقوق النشر 2025',
    'footer.companyDescription': 'CoinClarity هي منصة متعددة الاستخدامات تشارك أفضل بيانات سوق العملات المشفرة في الوقت الفعلي وأعلى جودة. مع واجهة برمجة تطبيقات سهلة الاستخدام والرسوم البيانية وقاموس العملات المشفرة.',
    
    'news.exclusiveTitle': 'أخبار حصرية',
    'news.viewAll': 'عرض الكل',
    'news.noNewsAvailable': 'لا توجد أخبار متاحة.',
    'news.by': 'بواسطة',
    'news.unknownAuthor': 'مؤلف غير معروف',
    'news.unknownDate': 'تاريخ غير معروف',
    'news.marketData': 'بيانات السوق',
    'news.cryptocurrency': 'العملات المشفرة',
    'news.nftMarket': 'سوق NFT',
    'news.viewChart': 'عرض الرسم البياني',
    'news.close': 'إغلاق',
    'news.timeRange': 'نطاق الوقت',
    'news.rank': 'الرتبة',
    'news.symbol': 'الرمز',
    'news.name': 'الاسم',
    'news.supply': 'العرض',
    'news.maxSupply': 'الحد الأقصى للعرض',
    'news.marketCap': 'القيمة السوقية',
    'news.volume24h': 'حجم 24 ساعة',
    'news.price': 'السعر',
    'news.change24h': 'التغيير في 24 ساعة',
    'news.floorPrice': 'السعر الأدنى',
    'news.floorPriceChange': 'تغيير السعر الأدنى',
    'news.showAll': 'عرض الكل',
    'news.showLess': 'عرض أقل',
    'news.loading': 'جاري التحميل...',
    'news.error': 'خطأ',
    'news.retry': 'إعادة المحاولة',
    'news.trendingTitle': 'الأخبار الرائجة',
    'news.readMore': 'اقرأ المزيد',
    'news.readFullArticle': 'اقرأ المقال كاملاً',
    'news.latestPressNews': 'أحدث الأخبار والبيانات الصحفية',
    'news.stayUpdated': 'ابق على اطلاع بآخر التطورات والإعلانات',
    
    // Explore section in Arabic
    'explore.didYouKnow': 'هل تعلم؟',
    'explore.learnALittle': 'تعلم قليلاً',
    'explore.testKnowledge': 'اختبر معرفتك',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('preferredLanguage', language);
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage][key as keyof typeof translations[typeof currentLanguage]];
    return translation || key;
  };

  // Load saved language preference on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
